from ucimlrepo import fetch_ucirepo 
#main.py FILE PY FOR EXECUTION THE APRIORI PROJECT.
# 
# EDUARDO JUNQUEIRA 
# TOPIC 1 ASSOCIATION RULES WITH APRIORI ALGORITHM PROJECT EDAMI
# 
#  ALL FILES .PY ARE EXECUTED HERE IN main.py
